# Etape de base pour les deux développements
FROM node:24-alpine AS base
WORKDIR /app
COPY package*.json ./

# Consignes de développement
FROM base AS development
RUN npm install
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]

# Consignes de build
FROM base AS build
RUN npm ci
COPY . .
RUN npm run build

FROM node:24-alpine AS production
WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=build /app/build ./build
COPY --from=build /app/static ./static

EXPOSE 3000
CMD ["node", "build/index.js"]