# Etape de base pour les deux développements
FROM node:24-alpine AS base
WORKDIR /app
COPY package*.json svelte.config.js ./

# Consignes de développement
FROM base AS development
RUN npm install
COPY . .
CMD ["npm", "run", "dev", "--", "--host"]

# Consignes de production
FROM base AS production
RUN npm ci
COPY . .

RUN npm run build

CMD ["npm", "run", "start"]